CDD/CDD/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path , include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('',include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

CDD/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('',home,name='home'),
    path('register/',register,name='register'),
    path('login/',user_login,name='login'),
    path('logout/', logout_view, name='logout'),
    path('upload/', upload, name='upload'),
    path('type/', type, name='plant_type'),
    path('board/', board, name='dashboard'),
    path('croprec/', Crop_Recommendation, name='crop_rec'),
]

CDD/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class Image(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to='disease_images/')

    def __str__(self):
        return f" - {self.image.name}"

class Disease(models.Model):
    disease = models.CharField(max_length=255)
    image = models.ForeignKey(Image,on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.disease} - {self.image.image.name}"

CDD/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login , logout
from django.http import HttpResponseRedirect,HttpResponse
from .models import profile
from django.contrib.auth.decorators import login_required
from .form import UploadImageForm
from .models import Image,Disease
import tensorflow as tf
from keras.models import load_model
import numpy as np
import pickle
import pandas as pd
from sklearn.impute import SimpleImputer
import sklearn
from django.conf import settings
from joblib import load
from django.utils.safestring import mark_safe



# model = load_model(r'accounts\\Models\\disease_detection.keras')
# Create your views here.
def home(request):
    return render(request,'index.html')

# Create your views here.
def register(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        c_password = request.POST.get('Cpassword')
        user_obj = User.objects.filter(username = email)

        if password != c_password:
            messages.warning(request, "Password does'nt matches")
            return HttpResponseRedirect(request.path_info)

        if user_obj.exists():
            messages.warning(request, 'Email is already taken.')
            return HttpResponseRedirect(request.path_info)

        print(email)

        user_obj = User.objects.create(first_name = username , email = email , username = email)
        user_obj.set_password(password)
        user_obj.save()

        messages.success(request, 'Successfully Registered.')
        return HttpResponseRedirect(request.path_info)


    return render(request ,'regis.html')


def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user_obj = User.objects.filter(username=email)

        if not user_obj.exists():
            messages.warning(request, 'Account not found.')
            return HttpResponseRedirect(request.path_info)

        user_obj = authenticate(username=email, password=password)
        if user_obj:
            login(request, user_obj)
            return redirect('/')
        messages.warning(request, 'Invalid credentials')
        return HttpResponseRedirect(request.path_info)

    return render(request, 'login.html')

@login_required
def logout_view(request):
    logout(request)
    # Optionally add logic here, e.g., messages or redirects
    return redirect('/')

@login_required
def upload(request):
    return render(request, 'upload.html')

@login_required
def type(request):
    return render(request, 'plant_type.html')

@login_required
def board(request):
    diseases = Disease.objects.filter(image__user=request.user)
    user = request.user
    return render(request, 'dashbord.html', {'diseases': diseases,'user':user})


class_names = ['Apple : Apple scab', 'Apple : Black rot', 'Apple : Cedar rust', 'Apple : Healthy',
               'Corn : Gray leaf spot', 'Corn : Common rust', 'Corn : Northern Leaf Blight', 'Corn : Healthy',
               'Grape : Black rot', 'Grape : Black Measles',  'Grape : Isariopsis Leaf Spot','Grape : Healthy',
               'Potato : Early blight',  'Potato : Late blight','Potato : Healthy',
               'Tomato : Bacterial spot', 'Tomato : Early blight', 'Tomato : Late blight', 'Tomato : Leaf Mold', 'Tomato : Yellow leaf curl virus', 'Tomato : Healthy'
               ]

def preprocess_image(image_path):
    img = tf.keras.preprocessing.image.load_img(image_path, target_size=(256, 256))
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0)  # Create batch axis
    return img_array

# def upload_image( request):
#     if request.method == 'POST':
#         form = UploadImageForm(request.POST, request.FILES)
#         if form.is_valid():
#             image_file = form.cleaned_data['image']
#             image_name = image_file.name  # Generate a unique filename (optional)


#             # Save image to database (assuming 'Image' model is defined)
#             user = request.user
#             image = Image(user = user,image=image_file)
#             image.save()
#             image_name.replace(' ', '-')
#             image_path = f'public\\static\\disease_images\\{image_name}'
#             image_array = preprocess_image(image_path)
#             print("IMAGE PATH IS :",image_path)
#             predictions = model.predict(image_array)
#             predicted_class_index = np.argmax(predictions[0])
#             predicted_class = class_names[predicted_class_index]
#             disease = Disease(disease=predicted_class, image=image)
#             disease.save()
#             disease_id = disease.id
#             disease = Disease.objects.get(pk=disease_id)
#             image_url = disease.image.image.url


#             return render(request, 'upload.html' ,  {'predicted_disease': predicted_class, 'url': image_url})
#     else:
#         form = UploadImageForm()

#     return render(request, 'upload.html', {'form': form})

def Crop_Recommendation(request):
    recommended_crop = ''
    if request.method == 'POST':
        nitrogen=request.POST.get('nitrogen')
        phosphorus = request.POST.get('phosphorus')
        potassium = request.POST.get('potassium')
        temperature = request.POST.get('temperature')
        humidity = request.POST.get('humidity')
        phLevel = request.POST.get('phLevel')
        rainfall = request.POST.get('rainfall')

        RF_joblib = r'accounts\\Models\\RandomForest.pkl'
        loaded_RF_model = load(RF_joblib)
        new_data = np.array([[nitrogen, phosphorus, potassium, temperature, humidity, phLevel, rainfall]])
        recommended_crop = loaded_RF_model.predict(new_data)
        recommended_crop = recommended_crop[0]

    return render(request, 'crop_rec.html',{'crop': recommended_crop})

CDD/templates/base/alert.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
 {{message}}
  </div>
  {% endfor %}
{% endif %}

CDD/templates/crop_rec.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Crop Recommendation</title>

        <script>
        function showHeading() {
        var heading = document.getElementById("myHeading");
        heading.style.display = "block";
        }
        </script>

        <!-- CSS FILES -->        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap" rel="stylesheet">
                        
        <link href="/media/css/bootstrap.min.css" rel="stylesheet">

        <link href="/media/css/bootstrap-icons.css" rel="stylesheet">

        <link href="/media/css/templatemo-topic-listing.css" rel="stylesheet">

        <link href="/media/css/style.css" rel="stylesheet">

        <script src="/media/js/script.js"></script>


<!--

TemplateMo 590 topic listing

https://templatemo.com/tm-590-topic-listing

-->
    </head>
    
    <body id="top">

        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'accounts:home' %}">
                        <i class="bi-back"></i>
                        <span>CRS</span>
                    </a>

                    <div class="d-lg-none ms-auto me-4">
                        <a href="#top" class="navbar-icon bi-person smoothscroll"></a>
                    </div>
    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
    
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ms-lg-5 me-lg-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>

                            </li>
                            
                            <li class="nav-item dropdown">

                                <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarLightDropdownMenuLink">
                                    <li><a class="dropdown-item" href="topics-listing.html">Topics Listing</a></li>

                                    <li><a class="dropdown-item" href="contact.html">Contact Form</a></li>
                                </ul>
                            </li>
                            
                        </ul>
                        

                        <div class="col-lg-3 col-md-4 col-12 mt-4 mt-lg-0 ms-auto" style="padding-left: 20%;">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle bi-person" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                </button>
    
                                <ul class="dropdown-menu">
                                    {% csrf_token %}
                                                                       <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:login' %}"><button class="dropdown-item" type="button">Login</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Login</button>
  {% endif %}
</li>

                                    <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:register' %}"><button class="dropdown-item" type="button">Register</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Register</button>
  {% endif %}
</li>
<li>
    {% if  user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}"><button class="dropdown-item" type="button">Logout</button></a>
    {% else %}
    <button class="dropdown-item" type="button" disabled >Logout</button></a>
    {% endif %}
</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            
            
            <section class="hero-section d-flex justify-content-center align-items-center " style="padding-top: 2%;" id="section_1">
              <div class="container-fluid" >
                <div class="row justify-content-center " >
                    <div class="container mt-5">
                        <div class="row justify-content-center ">
                          <div class="col-md-6 "style="height: 50%;">
                            <div class="card  shadow-lg my-div animate fadein" >
                                <h2 style="align-items: center; text-align: center;">Get the Crop Recommendation</h2>
                              <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}
                                    {% include "base/alert.html" %}
                                    <div class="row mb-3">
                                      <label for="nitrogen" class="col-sm-3 col-form-label">Nitrogen</label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="nitrogen" name="nitrogen" step="any" required>
                                      </div>
                                    </div>
                                    <div class="row mb-3">
                                      <label for="phosphorus" class="col-sm-3 col-form-label">Phosphorus</label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="phosphorus" name="phosphorus" step="any" required>
                                      </div>
                                    </div>
                                    <div class="row mb-3">
                                      <label for="potassium" class="col-sm-3 col-form-label">Potassium </label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="potassium" name="potassium" step="any" required>
                                      </div>
                                    </div>
                                    <div class="row mb-3">
                                      <label for="temperature" class="col-sm-3 col-form-label">Temperature</label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="temperature" name="temperature" step="any" required>
                                      </div>
                                    </div>
                                    <div class="row mb-3">
                                      <label for="humidity" class="col-sm-3 col-form-label">Humidity</label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="humidity" name="humidity" step="any" required>
                                      </div>
                                    </div>
                                    <div class="row mb-3">
                                      <label for="phLevel" class="col-sm-3 col-form-label">pH Level</label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="phLevel" name="phLevel" step="any" required>
                                      </div>
                                    </div>
                                    <div class="row mb-3">
                                      <label for="rainfall" class="col-sm-3 col-form-label">Rainfall</label>
                                      <div class="col-sm-9">
                                        <input type="number" class="form-control" id="rainfall" name="rainfall" step="any" required>
                                      </div>
                                    </div>

                                    <button type="submit" class="btn btn-primary " onclick="showHeading()">Submit</button>
                                  </form>
                                  <div>
                                        <h3 style="text-align:center">  {{ crop }} </h3>
                                    </div>
<!--                                  <h3 id="myHeading" style="display: none;"></h3>-->

                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                  </div>
                </div>

            </section>
        </main>
 
        <footer >
            
        </footer>
        <script>
            document.getElementById("loginForm").addEventListener("submit", function(event) {
              event.preventDefault(); 
              window.location.href = "dashbord.html";
            });
          </script>


        <!-- JAVASCRIPT FILES -->
        <script src="/media/js/jquery.min.js"></script>
        <script src="/media/js/bootstrap.bundle.min.js"></script>
        <script src="/media/js/jquery.sticky.js"></script>
        <script src="/media/js/click-scroll.js"></script>
        <script src="/media/js/custom.js"></script>

    </body>
</html>

CDD/templates/index.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <title>Crop Recommendation System</title>
                        
        <link href="/media/css/bootstrap.min.css" rel="stylesheet">

        <link href="/media/css/bootstrap-icons.css" rel="stylesheet">

        <link href="/media/css/templatemo-topic-listing.css" rel="stylesheet">

        <link href="/media/css/style.css" rel="stylesheet">

        <script src="/media/js/script.js"></script>

    </head>
    
    <body id="top">

        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'accounts:home' %}">
                        <i class="bi-back"></i>
                        <span>CRS</span>
                    </a>

                    <div class="d-lg-none ms-auto me-4">
                        <a href="#top" class="navbar-icon bi-person smoothscroll"></a>
                    </div>
    
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
    
                    <div class="collapse navbar-collapse" id="navbarNav" >
                        <ul class="navbar-nav ms-lg-5 me-lg-auto">
                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="#section_1">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="#section_2">Services</a>
                            </li>
    
                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="#section_3">How it works</a>
                            </li>

                            <!--
                            <li class="nav-item">
                                <a class="nav-link click-scroll" href="#section_4">FAQs</a>
                            </li>
                            -->
<!--                            <li class="nav-item">-->
<!--                                <a class="nav-link click-scroll" href="#section_5">Contact</a>-->
<!--                            </li>-->
                        </ul>
                        <div class="col-lg-3 col-md-4 col-12 mt-4 mt-lg-0 ms-auto"  style="padding-left: 20%;">
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle bi-person" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                </button>
    
                                <ul class="dropdown-menu">
                                    {% csrf_token %}
                                                                       <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:login' %}"><button class="dropdown-item" type="button">Login</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Login</button>
  {% endif %}
</li>

                                    <li>
  {% if not user.is_authenticated %}
    <a href="{% url 'accounts:register' %}"><button class="dropdown-item" type="button">Register</button></a>
  {% else %}
    <button class="dropdown-item disabled" type="button" disabled>Register</button>
  {% endif %}
</li>
<li>
    {% if  user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}"><button class="dropdown-item" type="button">Logout</button></a>
    {% else %}
    <button class="dropdown-item" type="button" disabled >Logout</button></a>
    {% endif %}
</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
            

            <section class="hero-section d-flex justify-content-center align-items-center" id="section_1">
                <div class="container">
                    <div class="row">

                        <div class=" mx-auto">
                            <h1 class="animated-heading text-white text-center">Crop Recommendation System</h1>

                        </div>

                    </div>
                </div>
            </section>

        
            <section class="featured-section">
                <div class="container">
                    
                </div>
            </section>


            <section class="explore-section section-padding" id="section_2">
                <div class="container">
                    <div class="row">

                        <div class="col-12 text-center">
                            <h2 class="mb-2">Crop Recommendation</h2>
                        </div>

                    </div>
                </div>
                <div class="col-12 text-center" >
              {% if not user.is_authenticated %}
            {% endif %}
            </div>

                <div class="container" >
                    <div class="row">
                        <div class="col-13">
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="design-tab-pane" role="tabpanel" aria-labelledby="design-tab" tabindex="0">
                                    <div class="row">
                                        <div class="col-lg-4 col-md-6 col-12 mb-4 mb-lg-0 ">
                                            <div class="custom-block bg-white shadow-lg">
                                                {% if user.is_authenticated %}
                                                <a href="{% url 'accounts:crop_rec' %}">
                                                    <div class="d-flex">
                                                        <div>
                                                            <h5 class="mb-2">Crop Recommendation</h5>

                                                                
                                                        </div>
                                                    </div>

                                                    <img src="/media/images/crop_rec.jpg" class="custom-block-image img-fluid" alt="">
                                                </a>
                                                {% else %}

                                                <a href="{% url 'accounts:register' %}">
                                                    <div class="d-flex">
                                                        <div>
                                                            <h5 class="mb-2">Crop Recommendation</h5>

                                                                
                                                        </div>
                                                    </div>

                                                    <img src="/media/images/crop_rec.jpg" class="custom-block-image img-fluid" alt="">
                                                    </a>
                                                {% endif %}
                                            </div>
                                        </div>



                    </div>
                </div>

            </section>


            <section class="timeline-section section-padding" id="section_3">
                <div class="section-overlay"></div>

                <div class="container">
                    <div class="row">

                        <div class="col-12 text-center">
                            <h2 class="text-white mb-4">How does it work?</h1>
                        </div>

                        <div class="col-lg-10 col-12 mx-auto">
                            <div class="timeline-container">
                                <ul class="vertical-scrollable-timeline" id="vertical-scrollable-timeline">
                                    <div class="list-progress">
                                        <div class="inner"></div>
                                    </div>


                                    <li>
                                        <h4 class="text-white mb-3">Crop Recommendation</h4>

                                        <p class="text-white">Enter the soil and climate details and get the Crop Recommendation based on the soil and the climate conditions </p>

<!--                                        <div class="icon-holder">-->
<!--                                          <i class=" bi-1-circle"></i>-->
<!--                                        </div>-->
                                    </li>


                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>




           </main>

<!--<footer class="site-footer" id="section_5">-->
<!--    <section class="section-padding section-bg">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div style="color: black; font-size: 60px; text-align: center;">Contact Us</div>-->

<!--                <div class="col-lg-12 col-12">-->
<!--                    <h3 class="mb-4 pb-2">We'd love to hear from you</h3>-->
<!--                </div>-->

<!--                <div class="col-lg-6 col-12">-->
<!--                    <form action="#" method="post" class="custom-form contact-form" role="form">-->
<!--                        <div class="row">-->
<!--                            <div class="col-lg-6 col-md-6 col-12">-->
<!--                                <div class="form-floating">-->
<!--                                    <input type="text" name="name" id="name" class="form-control" placeholder="Name" required="">-->

<!--                                    <label for="floatingInput">Name</label>-->
<!--                                </div>-->
<!--                            </div>-->

<!--                            <div class="col-lg-6 col-md-6 col-12">-->
<!--                                <div class="form-floating">-->
<!--                                    <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required="">-->

<!--                                    <label for="floatingInput">Email address</label>-->
<!--                                </div>-->
<!--                            </div>-->

<!--                            <div class="col-lg-12 col-12">-->
<!--                                <div class="form-floating">-->
<!--                                    <input type="text" name="subject" id="name" class="form-control" placeholder="Name" required="">-->

<!--                                    <label for="floatingInput">Subject</label>-->
<!--                                </div>-->

<!--                                <div class="form-floating">-->
<!--                                    <textarea class="form-control" id="message" name="message" placeholder="Tell me about the project"></textarea>-->

<!--                                    <label for="floatingTextarea">Tell me about the project</label>-->
<!--                                </div>-->
<!--                            </div>-->

<!--                            <div class="col-lg-4 col-12 ms-auto">-->
<!--                                <button type="submit" class="form-control">Submit</button>-->
<!--                            </div>-->

<!--                        </div>-->
<!--                    </form>-->
<!--                </div>-->

<!--                <div class="col-lg-5 col-12 mx-auto mt-5 mt-lg-0">-->
<!--                    <img src="/media/images/conta.jpg" alt="" width="600px" height="300px">-->


<!--                </div>-->

<!--            </div>-->
<!--        </div>-->
<!--    </section>-->
<!--        </footer>-->


        <!-- JAVASCRIPT FILES -->
        <script src="/media/js/jquery.min.js"></script>
        <script src="/media/js/bootstrap.bundle.min.js"></script>
        <script src="/media/js/jquery.sticky.js"></script>
        <script src="/media/js/click-scroll.js"></script>
        <script src="/media/js/custom.js"></script>

    </body>
</html>